/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.App;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AppList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-27T15:47:31.669Z")
public class AppList {
  @SerializedName("next_cursor")
  private String nextCursor = null;

  @SerializedName("items")
  private List<App> items = new ArrayList<App>();

   /**
   * Cursor to send with subsequent request to receive the next page, if non-empty.
   * @return nextCursor
  **/
  @ApiModelProperty(value = "Cursor to send with subsequent request to receive the next page, if non-empty.")
  public String getNextCursor() {
    return nextCursor;
  }

  public AppList items(List<App> items) {
    this.items = items;
    return this;
  }

  public AppList addItemsItem(App itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(required = true, value = "")
  public List<App> getItems() {
    return items;
  }

  public void setItems(List<App> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppList appList = (AppList) o;
    return Objects.equals(this.nextCursor, appList.nextCursor) &&
        Objects.equals(this.items, appList.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextCursor, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppList {\n");
    
    sb.append("    nextCursor: ").append(toIndentedString(nextCursor)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

