/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Stat;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Call
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-27T15:47:31.669Z")
public class Call {
  @SerializedName("id")
  private String id = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("app_id")
  private String appId = null;

  @SerializedName("fn_id")
  private String fnId = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("started_at")
  private OffsetDateTime startedAt = null;

  @SerializedName("completed_at")
  private OffsetDateTime completedAt = null;

  @SerializedName("stats")
  private List<Stat> stats = null;

   /**
   * Call ID.
   * @return id
  **/
  @ApiModelProperty(value = "Call ID.")
  public String getId() {
    return id;
  }

   /**
   * Call execution status.
   * @return status
  **/
  @ApiModelProperty(value = "Call execution status.")
  public String getStatus() {
    return status;
  }

   /**
   * Call execution error, if status is &#39;error&#39;.
   * @return error
  **/
  @ApiModelProperty(value = "Call execution error, if status is 'error'.")
  public String getError() {
    return error;
  }

   /**
   * App ID of fn that executed this call.
   * @return appId
  **/
  @ApiModelProperty(value = "App ID of fn that executed this call.")
  public String getAppId() {
    return appId;
  }

   /**
   * Fn ID of fn that executed this call.
   * @return fnId
  **/
  @ApiModelProperty(value = "Fn ID of fn that executed this call.")
  public String getFnId() {
    return fnId;
  }

   /**
   * Time when call was submitted. Always in UTC.
   * @return createdAt
  **/
  @ApiModelProperty(value = "Time when call was submitted. Always in UTC.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

   /**
   * Time when call started execution. Always in UTC.
   * @return startedAt
  **/
  @ApiModelProperty(value = "Time when call started execution. Always in UTC.")
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

   /**
   * Time when call completed, whether it was successul or failed. Always in UTC.
   * @return completedAt
  **/
  @ApiModelProperty(value = "Time when call completed, whether it was successul or failed. Always in UTC.")
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

   /**
   * A histogram of stats for a call, each is a snapshot of a calls state at the timestamp.
   * @return stats
  **/
  @ApiModelProperty(value = "A histogram of stats for a call, each is a snapshot of a calls state at the timestamp.")
  public List<Stat> getStats() {
    return stats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Call call = (Call) o;
    return Objects.equals(this.id, call.id) &&
        Objects.equals(this.status, call.status) &&
        Objects.equals(this.error, call.error) &&
        Objects.equals(this.appId, call.appId) &&
        Objects.equals(this.fnId, call.fnId) &&
        Objects.equals(this.createdAt, call.createdAt) &&
        Objects.equals(this.startedAt, call.startedAt) &&
        Objects.equals(this.completedAt, call.completedAt) &&
        Objects.equals(this.stats, call.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, error, appId, fnId, createdAt, startedAt, completedAt, stats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Call {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    fnId: ").append(toIndentedString(fnId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

