/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StatMetrics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-27T15:47:31.669Z")
public class StatMetrics {
  @SerializedName("net_rx")
  private Long netRx = null;

  @SerializedName("net_tx")
  private Long netTx = null;

  @SerializedName("mem_limit")
  private Long memLimit = null;

  @SerializedName("mem_usage")
  private Long memUsage = null;

  @SerializedName("disk_read")
  private Long diskRead = null;

  @SerializedName("disk_write")
  private Long diskWrite = null;

  @SerializedName("cpu_user")
  private Long cpuUser = null;

  @SerializedName("cpu_total")
  private Long cpuTotal = null;

  @SerializedName("cpu_kernel")
  private Long cpuKernel = null;

  public StatMetrics netRx(Long netRx) {
    this.netRx = netRx;
    return this;
  }

   /**
   * Get netRx
   * @return netRx
  **/
  @ApiModelProperty(value = "")
  public Long getNetRx() {
    return netRx;
  }

  public void setNetRx(Long netRx) {
    this.netRx = netRx;
  }

  public StatMetrics netTx(Long netTx) {
    this.netTx = netTx;
    return this;
  }

   /**
   * Get netTx
   * @return netTx
  **/
  @ApiModelProperty(value = "")
  public Long getNetTx() {
    return netTx;
  }

  public void setNetTx(Long netTx) {
    this.netTx = netTx;
  }

  public StatMetrics memLimit(Long memLimit) {
    this.memLimit = memLimit;
    return this;
  }

   /**
   * Get memLimit
   * @return memLimit
  **/
  @ApiModelProperty(value = "")
  public Long getMemLimit() {
    return memLimit;
  }

  public void setMemLimit(Long memLimit) {
    this.memLimit = memLimit;
  }

  public StatMetrics memUsage(Long memUsage) {
    this.memUsage = memUsage;
    return this;
  }

   /**
   * Get memUsage
   * @return memUsage
  **/
  @ApiModelProperty(value = "")
  public Long getMemUsage() {
    return memUsage;
  }

  public void setMemUsage(Long memUsage) {
    this.memUsage = memUsage;
  }

  public StatMetrics diskRead(Long diskRead) {
    this.diskRead = diskRead;
    return this;
  }

   /**
   * Get diskRead
   * @return diskRead
  **/
  @ApiModelProperty(value = "")
  public Long getDiskRead() {
    return diskRead;
  }

  public void setDiskRead(Long diskRead) {
    this.diskRead = diskRead;
  }

  public StatMetrics diskWrite(Long diskWrite) {
    this.diskWrite = diskWrite;
    return this;
  }

   /**
   * Get diskWrite
   * @return diskWrite
  **/
  @ApiModelProperty(value = "")
  public Long getDiskWrite() {
    return diskWrite;
  }

  public void setDiskWrite(Long diskWrite) {
    this.diskWrite = diskWrite;
  }

  public StatMetrics cpuUser(Long cpuUser) {
    this.cpuUser = cpuUser;
    return this;
  }

   /**
   * Get cpuUser
   * @return cpuUser
  **/
  @ApiModelProperty(value = "")
  public Long getCpuUser() {
    return cpuUser;
  }

  public void setCpuUser(Long cpuUser) {
    this.cpuUser = cpuUser;
  }

  public StatMetrics cpuTotal(Long cpuTotal) {
    this.cpuTotal = cpuTotal;
    return this;
  }

   /**
   * Get cpuTotal
   * @return cpuTotal
  **/
  @ApiModelProperty(value = "")
  public Long getCpuTotal() {
    return cpuTotal;
  }

  public void setCpuTotal(Long cpuTotal) {
    this.cpuTotal = cpuTotal;
  }

  public StatMetrics cpuKernel(Long cpuKernel) {
    this.cpuKernel = cpuKernel;
    return this;
  }

   /**
   * Get cpuKernel
   * @return cpuKernel
  **/
  @ApiModelProperty(value = "")
  public Long getCpuKernel() {
    return cpuKernel;
  }

  public void setCpuKernel(Long cpuKernel) {
    this.cpuKernel = cpuKernel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatMetrics statMetrics = (StatMetrics) o;
    return Objects.equals(this.netRx, statMetrics.netRx) &&
        Objects.equals(this.netTx, statMetrics.netTx) &&
        Objects.equals(this.memLimit, statMetrics.memLimit) &&
        Objects.equals(this.memUsage, statMetrics.memUsage) &&
        Objects.equals(this.diskRead, statMetrics.diskRead) &&
        Objects.equals(this.diskWrite, statMetrics.diskWrite) &&
        Objects.equals(this.cpuUser, statMetrics.cpuUser) &&
        Objects.equals(this.cpuTotal, statMetrics.cpuTotal) &&
        Objects.equals(this.cpuKernel, statMetrics.cpuKernel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(netRx, netTx, memLimit, memUsage, diskRead, diskWrite, cpuUser, cpuTotal, cpuKernel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatMetrics {\n");
    
    sb.append("    netRx: ").append(toIndentedString(netRx)).append("\n");
    sb.append("    netTx: ").append(toIndentedString(netTx)).append("\n");
    sb.append("    memLimit: ").append(toIndentedString(memLimit)).append("\n");
    sb.append("    memUsage: ").append(toIndentedString(memUsage)).append("\n");
    sb.append("    diskRead: ").append(toIndentedString(diskRead)).append("\n");
    sb.append("    diskWrite: ").append(toIndentedString(diskWrite)).append("\n");
    sb.append("    cpuUser: ").append(toIndentedString(cpuUser)).append("\n");
    sb.append("    cpuTotal: ").append(toIndentedString(cpuTotal)).append("\n");
    sb.append("    cpuKernel: ").append(toIndentedString(cpuKernel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

