/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Call;
import io.swagger.client.model.CallList;
import io.swagger.client.model.Error;
import io.swagger.client.model.Log;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CallApi
 */
@Ignore
public class CallApiTest {

    private final CallApi api = new CallApi();

    
    /**
     * Get call information
     *
     * Get call information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fnsFnIDCallsCallIDGetTest() throws ApiException {
        String fnID = null;
        String callID = null;
        Call response = api.fnsFnIDCallsCallIDGet(fnID, callID);

        // TODO: test validations
    }
    
    /**
     * Get a fns calls.
     *
     * Get a functions calls, results returned in created_at, descending order (newest first).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fnsFnIDCallsGetTest() throws ApiException {
        String fnID = null;
        String cursor = null;
        Integer perPage = null;
        Integer fromTime = null;
        Integer toTime = null;
        CallList response = api.fnsFnIDCallsGet(fnID, cursor, perPage, fromTime, toTime);

        // TODO: test validations
    }
    
    /**
     * Get logs for a call.
     *
     * Get logs for a call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCallLogsTest() throws ApiException {
        String fnID = null;
        String callID = null;
        Log response = api.getCallLogs(fnID, callID);

        // TODO: test validations
    }
    
}
