/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.Fn;
import io.swagger.client.model.FnList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FnsApi
 */
@Ignore
public class FnsApiTest {

    private final FnsApi api = new FnsApi();

    
    /**
     * Create A New Function
     *
     * Creates a new Function, returning the complete entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFnTest() throws ApiException {
        Fn body = null;
        Fn response = api.createFn(body);

        // TODO: test validations
    }
    
    /**
     * Delete A Function
     *
     * Delete the specified Function.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFnTest() throws ApiException {
        String fnID = null;
        api.deleteFn(fnID);

        // TODO: test validations
    }
    
    /**
     * Get Definition Of A Function
     *
     * Gets the definition for the Function with the specified ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFnTest() throws ApiException {
        String fnID = null;
        Fn response = api.getFn(fnID);

        // TODO: test validations
    }
    
    /**
     * Get A list Of Functions Within An Application
     *
     * Get a filtered list of Functions for an Application, in alphabetical order.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFnsTest() throws ApiException {
        String appId = null;
        String cursor = null;
        Integer perPage = null;
        String name = null;
        FnList response = api.listFns(appId, cursor, perPage, name);

        // TODO: test validations
    }
    
    /**
     * Update A Function
     *
     * Updates a Function via merging the provided values.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFnTest() throws ApiException {
        String fnID = null;
        Fn body = null;
        Fn response = api.updateFn(fnID, body);

        // TODO: test validations
    }
    
}
