/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.Log;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogApi
 */
@Ignore
public class LogApiTest {

    private final LogApi api = new LogApi();

    
    /**
     * Get logs for a call.
     *
     * Get logs for a call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCallLogsTest() throws ApiException {
        String fnID = null;
        String callID = null;
        Log response = api.getCallLogs(fnID, callID);

        // TODO: test validations
    }
    
}
