/*
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.Call;
import io.swagger.client.model.CallList;
import io.swagger.client.model.Error;
import io.swagger.client.model.Log;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CallApi {
    private ApiClient apiClient;

    public CallApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CallApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for fnsFnIDCallsCallIDGet
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call fnsFnIDCallsCallIDGetCall(String fnID, String callID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/fns/{fnID}/calls/{callID}"
            .replaceAll("\\{" + "fnID" + "\\}", apiClient.escapeString(fnID.toString()))
            .replaceAll("\\{" + "callID" + "\\}", apiClient.escapeString(callID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call fnsFnIDCallsCallIDGetValidateBeforeCall(String fnID, String callID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'fnID' is set
        if (fnID == null) {
            throw new ApiException("Missing the required parameter 'fnID' when calling fnsFnIDCallsCallIDGet(Async)");
        }
        
        // verify the required parameter 'callID' is set
        if (callID == null) {
            throw new ApiException("Missing the required parameter 'callID' when calling fnsFnIDCallsCallIDGet(Async)");
        }
        

        com.squareup.okhttp.Call call = fnsFnIDCallsCallIDGetCall(fnID, callID, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Get call information
     * Get call information
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @return Call
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Call fnsFnIDCallsCallIDGet(String fnID, String callID) throws ApiException {
        ApiResponse<Call> resp = fnsFnIDCallsCallIDGetWithHttpInfo(fnID, callID);
        return resp.getData();
    }

    /**
     * Get call information
     * Get call information
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @return ApiResponse&lt;Call&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Call> fnsFnIDCallsCallIDGetWithHttpInfo(String fnID, String callID) throws ApiException {
        com.squareup.okhttp.Call call = fnsFnIDCallsCallIDGetValidateBeforeCall(fnID, callID, null, null);
        Type localVarReturnType = new TypeToken<Call>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get call information (asynchronously)
     * Get call information
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call fnsFnIDCallsCallIDGetAsync(String fnID, String callID, final ApiCallback<Call> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = fnsFnIDCallsCallIDGetValidateBeforeCall(fnID, callID, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Call>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for fnsFnIDCallsGet
     * @param fnID Opaque, unique Function ID. (required)
     * @param cursor Cursor from previous response.next_cursor to begin results after, if any. (optional)
     * @param perPage Number of results to return, defaults to 30. Max of 100. (optional)
     * @param fromTime Unix timestamp in seconds, of call.created_at to begin the results at, default 0. (optional)
     * @param toTime Unix timestamp in seconds, of call.created_at to end the results at, defaults to latest. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call fnsFnIDCallsGetCall(String fnID, String cursor, Integer perPage, Integer fromTime, Integer toTime, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/fns/{fnID}/calls"
            .replaceAll("\\{" + "fnID" + "\\}", apiClient.escapeString(fnID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (cursor != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("cursor", cursor));
        if (perPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("per_page", perPage));
        if (fromTime != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("from_time", fromTime));
        if (toTime != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("to_time", toTime));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call fnsFnIDCallsGetValidateBeforeCall(String fnID, String cursor, Integer perPage, Integer fromTime, Integer toTime, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'fnID' is set
        if (fnID == null) {
            throw new ApiException("Missing the required parameter 'fnID' when calling fnsFnIDCallsGet(Async)");
        }
        

        com.squareup.okhttp.Call call = fnsFnIDCallsGetCall(fnID, cursor, perPage, fromTime, toTime, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Get a fns calls.
     * Get a functions calls, results returned in created_at, descending order (newest first).
     * @param fnID Opaque, unique Function ID. (required)
     * @param cursor Cursor from previous response.next_cursor to begin results after, if any. (optional)
     * @param perPage Number of results to return, defaults to 30. Max of 100. (optional)
     * @param fromTime Unix timestamp in seconds, of call.created_at to begin the results at, default 0. (optional)
     * @param toTime Unix timestamp in seconds, of call.created_at to end the results at, defaults to latest. (optional)
     * @return CallList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CallList fnsFnIDCallsGet(String fnID, String cursor, Integer perPage, Integer fromTime, Integer toTime) throws ApiException {
        ApiResponse<CallList> resp = fnsFnIDCallsGetWithHttpInfo(fnID, cursor, perPage, fromTime, toTime);
        return resp.getData();
    }

    /**
     * Get a fns calls.
     * Get a functions calls, results returned in created_at, descending order (newest first).
     * @param fnID Opaque, unique Function ID. (required)
     * @param cursor Cursor from previous response.next_cursor to begin results after, if any. (optional)
     * @param perPage Number of results to return, defaults to 30. Max of 100. (optional)
     * @param fromTime Unix timestamp in seconds, of call.created_at to begin the results at, default 0. (optional)
     * @param toTime Unix timestamp in seconds, of call.created_at to end the results at, defaults to latest. (optional)
     * @return ApiResponse&lt;CallList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CallList> fnsFnIDCallsGetWithHttpInfo(String fnID, String cursor, Integer perPage, Integer fromTime, Integer toTime) throws ApiException {
        com.squareup.okhttp.Call call = fnsFnIDCallsGetValidateBeforeCall(fnID, cursor, perPage, fromTime, toTime, null, null);
        Type localVarReturnType = new TypeToken<CallList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get a fns calls. (asynchronously)
     * Get a functions calls, results returned in created_at, descending order (newest first).
     * @param fnID Opaque, unique Function ID. (required)
     * @param cursor Cursor from previous response.next_cursor to begin results after, if any. (optional)
     * @param perPage Number of results to return, defaults to 30. Max of 100. (optional)
     * @param fromTime Unix timestamp in seconds, of call.created_at to begin the results at, default 0. (optional)
     * @param toTime Unix timestamp in seconds, of call.created_at to end the results at, defaults to latest. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call fnsFnIDCallsGetAsync(String fnID, String cursor, Integer perPage, Integer fromTime, Integer toTime, final ApiCallback<CallList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = fnsFnIDCallsGetValidateBeforeCall(fnID, cursor, perPage, fromTime, toTime, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CallList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCallLogs
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCallLogsCall(String fnID, String callID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/fns/{fnID}/calls/{callID}/log"
            .replaceAll("\\{" + "fnID" + "\\}", apiClient.escapeString(fnID.toString()))
            .replaceAll("\\{" + "callID" + "\\}", apiClient.escapeString(callID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCallLogsValidateBeforeCall(String fnID, String callID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'fnID' is set
        if (fnID == null) {
            throw new ApiException("Missing the required parameter 'fnID' when calling getCallLogs(Async)");
        }
        
        // verify the required parameter 'callID' is set
        if (callID == null) {
            throw new ApiException("Missing the required parameter 'callID' when calling getCallLogs(Async)");
        }
        

        com.squareup.okhttp.Call call = getCallLogsCall(fnID, callID, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Get logs for a call.
     * Get logs for a call.
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @return Log
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Log getCallLogs(String fnID, String callID) throws ApiException {
        ApiResponse<Log> resp = getCallLogsWithHttpInfo(fnID, callID);
        return resp.getData();
    }

    /**
     * Get logs for a call.
     * Get logs for a call.
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @return ApiResponse&lt;Log&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Log> getCallLogsWithHttpInfo(String fnID, String callID) throws ApiException {
        com.squareup.okhttp.Call call = getCallLogsValidateBeforeCall(fnID, callID, null, null);
        Type localVarReturnType = new TypeToken<Log>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get logs for a call. (asynchronously)
     * Get logs for a call.
     * @param fnID Opaque, unique Function ID. (required)
     * @param callID Opaque, unique Call ID. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCallLogsAsync(String fnID, String callID, final ApiCallback<Log> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCallLogsValidateBeforeCall(fnID, callID, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Log>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
